### ISSUE TITLE
Problem with "-" inside the role-name

### ISSUE THREAD

**Issue by fgoebel** [jam82/ansible-role-skeleton#2]
Hello, this is just to document that if one uses a "-" in the rolename after the "ansible-role-" prefix, for example "ansible-role-keycloak-admin", it will result in an invalid ansible var at 

- [defaults/main.yml](https://github.com/jam82/ansible-role-skeleton/blob/27bb7563e54c029fa377f6155d632bbff23706a3/defaults/main.yml.j2#L7)
- [tasks/main.yml](https://github.com/jam82/ansible-role-skeleton/blob/27bb7563e54c029fa377f6155d632bbff23706a3/tasks/main.yml.j2#L7)

**Comment by jomrr** [comment]
thanks, extended the replace... forgot that after renaming from ansible-skeleton to ansible-role-skeleton :)

**Comment by jam82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/wIp6iubY/1-test)
